theme: jekyll-theme-cayman
github:
  is_project_page: false 
copyright: false
footer: false
footer-display: false
footer-display: none
github:
  footer: false
github:
  footer-display: false
github:
  footer-display: none
